name: poweruptime-local-dev

services:
  poweruptime-db:
    container_name: poweruptime-db
    image: postgres:17.7-bookworm
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data:z
    environment:
      POSTGRES_DB: poweruptime
      POSTGRES_USER: poweruptime
      POSTGRES_PASSWORD: poweruptime
    ports:
      - '5432:5432'
    networks:
      - poweruptime-local-dev-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  poweruptime-rabbitmq:
    container_name: poweruptime-rabbitmq
    image: rabbitmq:4.2.2-management
    restart: unless-stopped
    volumes:
      - rabbit:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=poweruptime
      - RABBITMQ_DEFAULT_PASS=poweruptime
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - poweruptime-local-dev-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  poweruptime-apprise:
    container_name: poweruptime-apprise
    image: caronc/apprise:1.3.0
    restart: unless-stopped
    user: '${UID}:${GID}'
    environment:
      - APPRISE_STATEFUL_MODE=disabled
      - APPRISE_WORKER_COUNT=1
      - LOG_LEVEL=debug
    ports:
      - '8000:8000'
    networks:
      - poweruptime-local-dev-network
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:8000/status']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  poweruptime-local-dev-network:

volumes:
  db:
  rabbit:
  backend:
