version: '3.8'

name: poweruptime-local-backend-dev

services:
  postgres:
    container_name: poweruptime-local-backend-dev-db
    image: postgres:17.2-bookworm
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data:z
    environment:
      POSTGRES_DB: poweruptime
      POSTGRES_USER: poweruptime
      POSTGRES_PASSWORD: poweruptime
    ports:
      - "5432:5432"
    networks:
      - poweruptime-local-backend-dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  rabbitmq:
    container_name: poweruptime-local-backend-dev-rabbit
    image: rabbitmq:4.0.5-management
    restart: unless-stopped
    volumes:
      - rabbit:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=poweruptime
      - RABBITMQ_DEFAULT_PASS=poweruptime
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - poweruptime-local-backend-dev-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  ntfy:
    container_name: poweruptime-local-backend-dev-ntfy
    image: binwiederhier/ntfy:v2.11.0
    restart: unless-stopped
    volumes:
      - ntfy:/etc/ntfy
    command:
      - serve
    environment:
      TZ: UTC    # optional: set desired timezone
      NTFY_LISTEN_HTTP: ":8085"
      NTFY_AUTH_FILE: /etc/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: read-only
      NTFY_CACHE_DURATION: 0
      NTFY_BEHIND_PROXY: false
      NTFY_WEB_ROOT: /
    ports:
      - "8085:8085"
    networks:
      - poweruptime-local-backend-dev-network
    healthcheck: # optional: remember to adapt the host:port to your environment
      test: [ "CMD-SHELL", "wget -q --tries=1 http://localhost:8085/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s

#  web:
#    container_name: poweruptime-local-backend-dev-web
#    restart: unless-stopped
#    build:
#      context: ../web
#    ports:
#      - "4200:4200"
#    networks:
#      - poweruptime-local-backend-dev-network

networks:
  poweruptime-local-backend-dev-network:

volumes:
  db:
  rabbit:
  ntfy:

