services:
  backend:
    container_name: poweruptime-backend-dev-backend
    restart: unless-stopped
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - backend:/var/lib/poweruptime
    environment:
      - POWERUPTIME_HOST=localhost:4000
      - DATABASE_HOST=poweruptime-local-backend-dev-db
      - DATABASE_PASSWORD=poweruptime
      - RABBIT_HOST=poweruptime-local-backend-dev-rabbit
      - RABBIT_PASSWORD=poweruptime
      - SWAGGER_ENABLED=true
      - TEMP_NOTIFICATIONS_ENABLED=true
      - MAIL_ENABLED=false
    networks:
      - poweruptime-local-backend-dev-network
    # No healthcheck possible as the container is distroless and therfore has no bash nor other tools to make requests

volumes:
  db:
  rabbit:
  backend:



