name: poweruptime-local-backend-dev

services:
  poweruptime-backend:
    container_name: poweruptime-backend
    restart: unless-stopped
    build:
      context: backend
    ports:
      - "8080:8080"
    depends_on:
      poweruptime-rabbitmq:
        condition: service_healthy
      poweruptime-db:
        condition: service_healthy
      poweruptime-apprise:
        condition: service_healthy
    volumes:
      - backend:/var/lib/poweruptime
    environment:
      - POWERUPTIME_HOST=localhost:4200
      - DATABASE_HOST=poweruptime-db
      - DATABASE_PASSWORD=poweruptime
      - RABBIT_HOST=poweruptime-rabbitmq
      - RABBIT_PASSWORD=poweruptime
      - SWAGGER_ENABLED=true
      - TEMP_NOTIFICATIONS_ENABLED=true
      - MAIL_ENABLED=false
      - MAIL_HOST=abc.xyz
      - MAIL_PORT=1234
      - MAIL_USERNAME=test
      - MAIL_PASSWORD=test
      - LOG_LEVEL=INFO
    networks:
      - poweruptime-local-backend-dev-network

networks:
  poweruptime-local-backend-dev-network:

volumes:
  db:
  rabbit:
  backend:
