name: poweruptime-local-backend-dev

services:
  postgres:
    container_name: poweruptime-local-backend-dev-db
    image: postgres:17.5-bookworm
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data:z
    environment:
      POSTGRES_DB: poweruptime
      POSTGRES_USER: poweruptime
      POSTGRES_PASSWORD: poweruptime
    ports:
      - "5432:5432"
    networks:
      - poweruptime-local-backend-dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  rabbitmq:
    container_name: poweruptime-local-backend-dev-rabbit
    image: rabbitmq:4.1.1-management
    restart: unless-stopped
    volumes:
      - rabbit:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=poweruptime
      - RABBITMQ_DEFAULT_PASS=poweruptime
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - poweruptime-local-backend-dev-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  apprise:
    container_name: poweruptime-local-backend-dev-apprise
    image: caronc/apprise:1.2.0
    restart: unless-stopped
    environment:
      - APPRISE_STATEFUL_MODE=disabled
      - APPRISE_WORKER_COUNT=1
      - LOG_LEVEL=debug
    ports:
      - "8000:8000"
    networks:
      - poweruptime-local-backend-dev-network
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  web:
    container_name: poweruptime-local-backend-dev-web
    restart: unless-stopped
    build:
      context: ../web
    ports:
      - "4210:4200"
    networks:
      - poweruptime-local-backend-dev-network
    healthcheck:
      test: ['CMD', 'wget', '-qO-', '--tries=1', 'http://localhost:4200']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  poweruptime-local-backend-dev-network:

volumes:
  db:
  rabbit:
