version: '3.8'

name: poweruptime-local-backend-dev

services:
  postgres:
    container_name: poweruptime-local-backend-dev-db
    image: postgres:17.4-bookworm
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data:z
    environment:
      POSTGRES_DB: poweruptime
      POSTGRES_USER: poweruptime
      POSTGRES_PASSWORD: poweruptime
    ports:
      - "5432:5432"
    networks:
      - poweruptime-local-backend-dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  rabbitmq:
    container_name: poweruptime-local-backend-dev-rabbit
    image: rabbitmq:4.0.8-management
    restart: unless-stopped
    volumes:
      - rabbit:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=poweruptime
      - RABBITMQ_DEFAULT_PASS=poweruptime
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - poweruptime-local-backend-dev-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

#  web:
#    container_name: poweruptime-local-backend-dev-web
#    restart: unless-stopped
#    build:
#      context: ../web
#    ports:
#      - "4210:4200"
#    networks:
#      - poweruptime-local-backend-dev-network

networks:
  poweruptime-local-backend-dev-network:

volumes:
  db:
  rabbit:

