server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: poweruptime-backend

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:poweruptime-db}:${DATABASE_PORT:5432}/${DATABASE_NAME:poweruptime}
    username: ${DATABASE_USER:poweruptime}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    listener:
      simple:
        default-requeue-rejected: 'false'
        concurrency: 8
        max-concurrency: 16

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
    path: /swagger/docs-json
  swagger-ui:
    path: /swagger/docs
    operationsSorter: alpha
    tagsSorter: alpha
  packagesToScan: org.poweruptime

logging:
  level:
    org.poweruptime: ERROR
    org.springframework.security: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR

management:
  health:
    mail:
      enabled: ${MAIL_ENABLED:true}

poweruptime:
  swagger: ${SWAGGER_ENABLED:false}
  host: ${POWERUPTIME_HOST}
  mail:
    enabled: ${MAIL_ENABLED:true}
  notification-temp:
    enabled: ${TEMP_NOTIFICATIONS_ENABLED:false}
  storage:
    directory: /var/lib/poweruptime/storage
  keys:
    directory: /var/lib/poweruptime/authentication-keys
    access-token:
      private: access-token-private.key
      public: access-token-public.key
    refresh-token:
      private: refresh-token-private.key
      public: refresh-token-public.key
  rate-limit:
    enabled: ${RATE_LIMIT_ENABLED:true}
    duration-in-seconds: ${RATE_LIMIT_DURATION_IN_SECONDS:240}
    tries: ${RATE_LIMIT_TRIES:40}
  push:
    enabled: ${PUSH_ENABLED:true}
