server:
  port: 8080
  servlet:
    context-path: /api

  tomcat:
    threads:
      max: 4

spring:
  application:
    name: poweruptime-backend

  main:
    allow-bean-definition-overriding: true
    banner-mode: off

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/poweruptime?reWriteBatchedInserts=true
    username: poweruptime
    password: poweruptime

  sql:
    init:
      mode: never

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: poweruptime
    password: poweruptime
    listener:
      simple:
        default-requeue-rejected: 'false'
        concurrency: 8
        max-concurrency: 16

  mail:
    host: smtp.google.com
    port: 587
    username: test@test.at
    password: test

  autoconfigure:
    exclude:
      - org.springframework.boot.security.oauth2.client.autoconfigure.OAuth2ClientAutoConfiguration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: EMPTY
            client-secret: EMPTY
            redirect-uri: http://localhost:8080/api/login/oauth2/code/google
            scope:
              - openid
              - profile
              - email

#          keycloak:
#            client-id: keycloakId
#            client-secret: keycloakSecret
#            provider: keycloak
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/api/login/oauth2/code/google
#            scope:
#              - openid
#              - email
#              - profile
#
#        provider:
#          keycloak:
#            authorization-uri: http://keycloak.io/realm/auth
#            issuer-uri: http://keycloak.io/realm/auth
#            jwk-set-uri: http://keycloak.io/realm/auth
#            token-uri: http://keycloak.io/realm/auth
#            user-info-uri: http://keycloak.io/realm/auth
#            user-name-attribute: sub

springdoc:
  api-docs:
    enabled: true
    path: /swagger/docs-json
  swagger-ui:
    path: /swagger/docs
    operationsSorter: alpha
    tagsSorter: alpha
  packagesToScan: org.poweruptime.backend


logging:
  level:
    org.poweruptime: DEBUG
#    Exposed: DEBUG
#    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, liquibase, metrics, scheduledtasks
  health:
    mail:
      enabled: false

poweruptime:
  swagger: true
  host: localhost:4200
  apprise:
    url: http://localhost:8000
  mail:
    enabled: false
    security: NONE_STARTTLS
    ignore-tls-errors: false # greenmail does not support STARTTLS
  notification-temp:
    enabled: false
  monitor-autostart:
    enabled: true
  storage:
    directory: storage
  keys:
    directory: keys/some
    access-token:
      private: access-token-private.key
      public: access-token-public.key
    refresh-token:
      private: refresh-token-private.key
      public: refresh-token-public.key
  rate-limit:
    enabled: true
    duration-in-seconds: 120
    tries: 20
  push:
    enabled: true
  database:
    ddl-auto: validate
