server:
  port: 8080
  servlet:
    context-path: /api

  tomcat:
    threads:
      max: 4

spring:
  application:
    name: poweruptime-backend

  main:
    allow-bean-definition-overriding: true
    banner-mode: off

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:poweruptime-db}:${DATABASE_PORT:5432}/${DATABASE_NAME:poweruptime}
    username: ${DATABASE_USERNAME:poweruptime}
    password: ${DATABASE_PASSWORD}

  sql:
    init:
      mode: never

  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

  rabbitmq:
    host: ${RABBIT_HOST:poweruptime-rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:poweruptime}
    password: ${RABBIT_PASSWORD}
    listener:
      simple:
        default-requeue-rejected: 'false'
        concurrency: ${RABBIT_LISTENER_CONCURRENCY:16}
        max-concurrency: ${RABBIT_LISTENER_MAX_CONCURRENCY:16}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientAutoConfiguration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID:EMPTY}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET:EMPTY}
            redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI:${POWERUPTIME_HOST}/api/login/oauth2/code/google}
            scope:
              - openid
              - email
              - profile

          keycloak:
            client-id: ${OAUTH2_KEYCLOAK_CLIENT_ID:EMPTY}
            client-secret: ${OAUTH2_KEYCLOAK_CLIENT_SECRET:EMPTY}
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: ${OAUTH2_KEYCLOAK_REDIRECT_URI:${POWERUPTIME_HOST}/api/login/oauth2/code/keycloak}
            scope:
              - openid
              - email
              - profile

        provider:
          keycloak:
            authorization-uri: ${OAUTH2_KEYCLOAK_AUTHORIZATION_URI:EMPTY}
            issuer-uri: ${OAUTH2_KEYCLOAK_ISSUER_URI:EMPTY}
            jwk-set-uri: ${OAUTH2_KEYCLOAK_JWK_SET_URI:EMPTY}
            token-uri: ${OAUTH2_KEYCLOAK_TOKEN_URI:EMPTY}
            user-info-uri: ${OAUTH2_KEYCLOAK_USER_INFO_URI:EMPTY}
            user-name-attribute: ${OAUTH2_KEYCLOAK_USER_NAME_ATTRIBUTE:sub}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
    path: /swagger/docs-json
  swagger-ui:
    path: /swagger/docs
    operationsSorter: alpha
    tagsSorter: alpha
  packagesToScan: org.poweruptime

logging:
  level:
    org.poweruptime: ${LOG_LEVEL:ERROR}
    org.springframework.security: ${LOG_LEVEL:ERROR}
    org.springframework.web: ${LOG_LEVEL:ERROR}
    org.hibernate: ${LOG_LEVEL:ERROR}

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    mail:
      enabled: ${MAIL_ENABLED:true}

poweruptime:
  swagger: ${SWAGGER_ENABLED:false}
  host: ${POWERUPTIME_HOST}
  apprise:
    url: ${POWERUPTIME_APPRISE_URL:http://poweruptime-apprise:8000}
  mail:
    enabled: ${MAIL_ENABLED:true}
    security: ${MAIL_SECURITY:NONE_STARTTLS}
    ignore-tls-errors: ${MAIL_IGNORE_TLS_ERRORS:false}
  notification-temp:
    enabled: ${TEMP_NOTIFICATIONS_ENABLED:false}
  storage:
    directory: /var/lib/poweruptime/storage
  keys:
    directory: /var/lib/poweruptime/authentication-keys
    access-token:
      private: access-token-private.key
      public: access-token-public.key
    refresh-token:
      private: refresh-token-private.key
      public: refresh-token-public.key
  rate-limit:
    enabled: ${RATE_LIMIT_ENABLED:true}
    duration-in-seconds: ${RATE_LIMIT_DURATION_IN_SECONDS:240}
    tries: ${RATE_LIMIT_TRIES:40}
  push:
    enabled: ${PUSH_ENABLED:true}
