package org.poweruptime.backend

import org.poweruptime.backend.core.utils.Config
import org.poweruptime.backend.features.fileUpload.FileService
import org.poweruptime.backend.features.info.InfoService
import org.poweruptime.backend.features.monitor.service.MonitorService
import org.poweruptime.backend.features.tempNotification.TempNotification
import org.poweruptime.backend.features.tempNotification.TempNotificationService
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Value
import org.springframework.context.ApplicationListener
import org.springframework.context.event.ContextRefreshedEvent
import org.springframework.stereotype.Component
import java.time.Instant

@Component
class StartupApplicationListener(
    private val tempNotificationService: TempNotificationService,
    private val monitorService: MonitorService,
    private val infoService: InfoService,
    private val fileService: FileService,
    @Value(Config.NOTIFICATION_TEMP_ENABLED) private val tempNotificationsEnabled: Boolean = false,
) : ApplicationListener<ContextRefreshedEvent> {

    private val log: Logger = LoggerFactory.getLogger(StartupApplicationListener::class.java)

    @Suppress("MaxLineLength", "LongMethod")
    override fun onApplicationEvent(event: ContextRefreshedEvent) {
        fileService.init()
        setupTempNotification()

        monitorService.startAll()
    }

    private fun setupTempNotification() {
        log.info("Temp tempNotification enabled: $tempNotificationsEnabled")
        if (tempNotificationsEnabled) {
            addTempNotification()
        }
    }

    private fun addTempNotification() {
        for (i in 1..3) {
            tempNotificationService.addNotification(
                TempNotification(
                    to = "INFORMATION",
                    subject = "Autogenerated Test $i",
                    body = "Welcome! Running ${infoService.name}! ( ͡° ͜ʖ ͡°) Version: " +
                        "${infoService.version} Build time: ${infoService.buildTime}",
                    bodyHTML = "Welcome! Running ${infoService.name}! ( ͡° ͜ʖ ͡°) <br>" +
                        "Version: ${infoService.version} <br> Build time: ${infoService.buildTime}",
                    createdAt = Instant.now().plusSeconds(TWO_DAYS_IN_SECONDS),
                ),
            )
        }
    }
}

const val TWO_DAYS_IN_SECONDS = (2 * 24 * 60 * 60).toLong()
