package org.poweruptime.backend

import io.github.oshai.kotlinlogging.KotlinLogging
import org.poweruptime.backend.core.utils.Config
import org.poweruptime.backend.core.utils.DateTimeUtils
import org.poweruptime.backend.features.fileUpload.FileService
import org.poweruptime.backend.features.info.InfoService
import org.poweruptime.backend.features.info.instanceSetting.InstanceSettingService
import org.poweruptime.backend.features.monitor.service.MonitorService
import org.poweruptime.backend.features.tempNotification.TempNotification
import org.poweruptime.backend.features.tempNotification.TempNotificationService
import org.springframework.beans.factory.annotation.Value
import org.springframework.context.ApplicationListener
import org.springframework.context.event.ContextRefreshedEvent
import org.springframework.stereotype.Component
import java.time.Instant

@Component
class StartupApplicationListener(
    private val tempNotificationService: TempNotificationService,
    private val monitorService: MonitorService,
    private val infoService: InfoService,
    private val fileService: FileService,
    private val instanceSettingService: InstanceSettingService,
    @param:Value(Config.NOTIFICATION_TEMP_ENABLED) private val tempNotificationsEnabled: Boolean = false,
) : ApplicationListener<ContextRefreshedEvent> {

    private final val logger = KotlinLogging.logger {}

    override fun onApplicationEvent(event: ContextRefreshedEvent) {
        logger.info {
            "Server setup time: ${DateTimeUtils.simpleDateTimeFormatter.format(
                instanceSettingService.serverSetupTime,
            )}"
        }

        fileService.init()
        setupTempNotification()

        monitorService.startAll()
    }

    private fun setupTempNotification() {
        fun addTempNotification() {
            for (i in 1..3) {
                tempNotificationService.addNotification(
                    TempNotification(
                        to = "INFORMATION",
                        subject = "Autogenerated Test $i",
                        body = "Welcome! Running ${infoService.name}! ( ͡° ͜ʖ ͡°) Version: " +
                            "${infoService.version} Build time: ${infoService.buildTime}",
                        bodyHTML = "Welcome! Running ${infoService.name}! ( ͡° ͜ʖ ͡°) <br>" +
                            "Version: ${infoService.version} <br> Build time: ${infoService.buildTime}",
                        createdAt = Instant.now().plusSeconds(TWO_DAYS_IN_SECONDS),
                    ),
                )
            }
        }

        logger.info { "Temp tempNotification enabled: $tempNotificationsEnabled" }
        if (tempNotificationsEnabled) {
            addTempNotification()
        }
    }
}

private const val TWO_DAYS_IN_SECONDS = (2 * 24 * 60 * 60).toLong()
