name: 'Setup Playwright'
description: 'Setup Playwright with caching, using pnpm (should already be installed)'
runs:
  using: 'composite'
  steps:
    - name: Extract Playwright version
      id: playwright-version
      shell: bash
      run: |
        cd web
        echo "PLAYWRIGHT_VERSION=$(jq -r '.devDependencies."@playwright/test"' package.json)" >> $GITHUB_ENV
        cd -

    - name: Cache Playwright
      id: playwright-cache
      uses: actions/cache@v5
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright dependencies
      shell: bash
      run: |
        # Avoid long delays on the "Processing triggers for man-db"
        # step during installation
        #
        # ```
        # pnpm playwright install --with-deps chrome
        # Installing dependencies...
        # Switching to root user to install dependencies...
        # ...
        # Processing triggers for man-db (2.12.0-4build2) ...
        # ```
        #
        # - https://github.com/actions/runner/issues/4030
        # - https://github.com/microsoft/playwright/issues/14434
        sudo apt-get --yes remove --purge man-db
        cd web
        pnpm exec playwright install --with-deps --only-shell
        cd -
