name: dev ci (translations)

on:
  push:
    branches:
      - main
    paths:
      - 'web/src/assets/i18n/**.json'
  pull_request:
    paths:
      - 'web/src/assets/i18n/**.json'

jobs:
  validate-translations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: dafnik/setup-node-pnpm@v5
        with:
          install-ignore-scripts: true

      - name: Validate changed i18n files
        run: |
          # Find the changed i18n files and run the validator on them
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'src/assets/i18n/.*\.json' | xargs pnpm -C web exec transloco-validator
