name: dev ci (web)

on:
  pull_request:
    paths:
      - '.github/**'
      - 'web/**'
      - '.gitignore'
      - '.npmrc'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'web/**'
      - '.npmrc'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dafnik/setup-node-pnpm@v5
        with:
          install-ignore-scripts: true

      - name: Build
        run: pnpm web:build:docker

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dafnik/setup-node-pnpm@v5
        with:
          install-ignore-scripts: true

      - name: Lint check
        run: pnpm web:lint
