name: web dev ci

on:
  push:
    branches:
      - '*' # matches every branch that doesn't contain a '/'
      - '*/*' # matches every branch containing a single '/'
      - '**' # matches every branch

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dafnik/setup-node-pnpm@v3
        with:
          install-ignore-scripts: true

      - name: Build
        run: pnpm build

  web-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dafnik/setup-node-pnpm@v3
        with:
          install-ignore-scripts: true

      - name: Style check
        run: pnpm format:check

  commitlint:
    name: Commitlint Check
    runs-on: ubuntu-latest
    steps:
      # Needed to get the commitlint config
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run commitlint
        uses: dafnik/commitlint@v1

  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Review Dog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run detekt
        run: ./gradlew detekt

      # SARIF-Upload/CodeQL is not available for private repositories (also not for team plan) :(
      # -> Use https://github.com/reviewdog/reviewdog to get a similar result
      - name: Add detekt result to PR
        if: success() || failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -f=sarif -name=detekt -reporter=github-pr-check < build/reports/detekt/merge.sarif

  email-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          cd emails
          npm ci
          cd -

      - name: run prettier
        run: cd emails && npm run format:check
