name: 'ghcr Cleanup'

on:
  workflow_dispatch:
  schedule:
    - cron: '00 4 * * sun' # At 04:00 on Sundays.

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cleanup ghcr untagged images
        uses: ./.github/actions/ghcr-cleanup
        with:
          dryrun: 'true'
          packages: 'web,backend'
          github-token: ${{ secrets.GITHUB_TOKEN }}
