name: Build and release docker images

on:
  push:
    tags:
      - '*.*.*-beta-*'
      - '*.*.*'

# We must only run one release workflow at a time to prevent corrupting
# our release artifacts.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  mirror-infra-beta:
    runs-on: ubuntu-latest
    if: contains(github.ref_name, 'beta')
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: Pushes to docker-compose repository on main branch
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.INFRA_MIRROR_DEPLOY_TOKEN }}
        with:
          source-directory: ./infrastructure
          destination-github-username: 'poweruptime'
          destination-repository-name: 'docker-compose'
          user-email: github-actions[bot]@users.noreply.github.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: beta
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY

  tag-infra-mirror-beta:
    runs-on: ubuntu-latest
    if: contains(github.ref_name, 'beta')
    needs: [mirror-infra-beta]
    steps:
      - name: Check out docker-compose repository
        uses: actions/checkout@v4
        with:
          repository: poweruptime/docker-compose
          ref: beta
          token: ${{ secrets.INFRA_MIRROR_TAG_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Tag ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.INFRA_MIRROR_TAG_TOKEN }}
        run: |
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}

  mirror-infra:
    runs-on: ubuntu-latest
    if: "!contains(github.ref_name, 'beta')"
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: Pushes to docker-compose repository on main branch
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.INFRA_MIRROR_DEPLOY_TOKEN }}
        with:
          source-directory: ./infrastructure
          destination-github-username: 'poweruptime'
          destination-repository-name: 'docker-compose'
          user-email: github-actions[bot]@users.noreply.github.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY

  tag-infra-mirror:
    runs-on: ubuntu-latest
    if: "!contains(github.ref_name, 'beta')"
    needs: [mirror-infra]
    steps:
      - name: Check out docker-compose repository
        uses: actions/checkout@v4
        with:
          repository: poweruptime/docker-compose
          ref: main
          token: ${{ secrets.INFRA_MIRROR_TAG_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Tag ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.INFRA_MIRROR_TAG_TOKEN }}
        run: |
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dafnik/setup-node-pnpm@v4
        with:
          install-ignore-scripts: true

      - name: Build
        run: NG_APP_VERSION=${{ github.ref_name }} pnpm web:build:prod

      - name: Archive web artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ./web/dist/poweruptime-web
          retention-days: 1

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build
        run: ./gradlew backend:build -x test -Pversion=${{ github.ref_name }} -Dspring.profiles.active=container --scan --no-daemon

      - name: Archive backend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: ./backend/build/libs/backend.jar
          retention-days: 1

  build-publish-docker:
    strategy:
      matrix:
        containers: [web, backend]
    needs: [build-backend, build-web]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download backend files
        if: contains(matrix.containers, 'backend')
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.containers }}
          path: ./backend/build/libs

      - name: Download web files
        if: contains(matrix.containers, 'web')
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.containers }}
          path: ./web/dist/poweruptime-web

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: version
        # 3.4.0-beta-12345 -> 3.4.0-beta
        run: |
          VERSION=${{ github.ref_name }}
          echo "version=${VERSION%-*}" >> "$GITHUB_OUTPUT"

      - name: Build and push beta Docker image
        if: contains(github.ref_name, 'beta')
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.containers }}
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            version=${{ github.ref_name }}
          # tags: 3.4.0-beta-12345678, 3.4.0-beta, latest-beta
          tags: |
            ghcr.io/poweruptime/${{ matrix.containers }}:${{ github.ref_name }}
            ghcr.io/poweruptime/${{ matrix.containers }}:${{ steps.version.outputs.version }}
            ghcr.io/poweruptime/${{ matrix.containers }}:latest-beta

      - name: Build and push prod Docker image
        if: "!contains(github.ref_name, 'beta')"
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.containers }}
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            version=${{ github.ref_name }}
          # tags: 3.4.0, latest
          tags: |
            ghcr.io/poweruptime/${{ matrix.containers }}:${{ github.ref_name }}
            ghcr.io/poweruptime/${{ matrix.containers }}:latest
