name: poweruptime-local-dev

services:
  poweruptime-web:
    container_name: poweruptime-web
    restart: unless-stopped
    depends_on:
      poweruptime-backend:
        condition: service_healthy
    build:
      context: web
    ports:
      - '4200:4200'
    networks:
      - poweruptime-local-dev-network
# localhost:4200 gets added automatically
#    environment:
#      - POWERUPTIME_HOST=localhost:4200
#      - DOMAIN_NAMES="Host(`status1.abc.xyz`) || Host(`status2.abc.xzy`)"

networks:
  poweruptime-local-dev-network:

volumes:
  db:
  rabbit:
  backend:
